#!/bin/bash
set -ouex pipefail

# Repository setup
sed -i 's/main/main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/*
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list
curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
tee /etc/apt/sources.list.d/zabbly-incus-stable.sources <<EOF
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: main
Signed-By: /etc/apt/keyrings/zabbly.asc
EOF

# Initial update
apt-get update -y

# Add nonfree firmware
apt-get install -y \
	firmware-linux-nonfree

# Ensure dracut is kept
apt autoremove -y --purge
apt-get install -y \
	dracut

# Oxidize
apt install -y \
	sudo-rs \
	rust-coreutils

# Distrobox
apt-get install -y \
	podman \
	distrobox

# Flatpak & Flathub
apt-get install -y \
	flatpak \
	curl

# Docker
apt-get install -y \
	docker-ce \
	docker-ce-cli \
	containerd.io \
	docker-buildx-plugin \
	docker-compose-plugin

# Incus
apt-get install -y \
	dnsmasq-base \
	ovmf \
	qemu-kvm \
	qemu-utils \
	qemu-system-gui \
	qemu-system-modules-spice \
	ipxe-qemu \
	genisoimage \
	virt-viewer \
	incus \
	incus-ui-canonical

mkdir -p /etc/flatpak/remotes.d
curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo

# GNOME Customization
apt-get install -y \
	gnome-shell-extension-appindicator

# locales and keyboard
apt-get install -y \
    locales \
    keyboard-configuration

# NetworkManager
apt-get install -y \
    network-manager \
    network-manager-applet

# Switch to IWD
apt-get install -y \
	iwd
apt-get remove -y \
	wpasupplicant
# Handle new user groups
echo 'GROUPS=users docker incus-admin' >> /etc/default/useradd

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
	--kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"

# Cleanup
apt autoremove -y --purge
