#!/bin/bash
set -ouex pipefail

# Repository setup
sed -i 's/main/main contrib non-free non-free-firmware/' /etc/apt/sources.list.d/*

# Initial update
apt-get update -y

# Add nonfree firmware
apt-get install -y \
	firmware-linux-nonfree

# Distrobox
apt-get install -y \
	podman \
	distrobox

# Flatpak & Flathub
apt-get install -y \
	flatpak \
	curl

mkdir -p /etc/flatpak/remotes.d
curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo

# GNOME Customization
apt-get install -y \
	gnome-shell-extension-appindicator \
	ptyxis
apt-get remove -y \
	gnome-terminal

# Switch to IWD
apt-get install -y \
	iwd
apt-get remove -y \
	wpasupplicant

# Handle new user groups
# sed -i 's|^GROUPS=.*|GROUPS=users docker incus-admin' "/etc/default/useradd"

# Cleanup
apt autoremove -y --purge
